# Generated by Django 5.2.6 on 2025-10-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_blog_blog_blog_category_blog_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
    ]
