# Generated by Django 5.2.6 on 2025-10-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_blog_category_remove_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
